### ISSUE TITLE
Using tensorflow estimator

### ISSUE THREAD

**Issue by TianrenWang** [deepmind/graph_nets#105]
How can I create GraphTuple from tensor objects rather than dictionary objects passed into the placeholder? The example uses something like this:
```
graphs_tuple_tf = utils_tf.data_dicts_to_graphs_tuple(graph_dicts)

with tf.Session() as sess:
  graphs_tuple_np = sess.run(graphs_tuple_tf)
```

but I want something like this:

```
node_tensor = some tensor operation
edge_tensor = some tensor operation
global_tensor = some tensor operation
.
.
.
graphs_tuple_tf = utils_tf.tensors_to_graphs_tuple(node_tensor, edge_tensor, global_tensor.......)
.
.
.
```
In an estimator the placeholder method wouldn't work because I cannot dynamically create dictionary objects to be fed into `utils_tf.data_dicts_to_graphs_tuple`.

**Comment by alvarosg** [comment]
Thanks for your message.

I am not sure I fully understand why it is not possible to create the dictionary. 

In principle the `utils_tf.data_dicts_to_graphs_tuple` can also be called with a `data_dict` containing tensors, so it is possible to do:
```
import tensorflow as tf
import graph_nets as gn

def get_random_graph_tensor_data_dict():
  num_nodes = tf.random_uniform(minval=10, maxval=20, shape=(), dtype=tf.int32)
  num_edges = tf.random_uniform(minval=50, maxval=100, shape=(), dtype=tf.int32)
  
  global_tensor = tf.zeros([5])  # 5 global features
  node_tensor = tf.zeros([num_nodes, 3])  # 3 node features
  edge_tensor = tf.zeros([num_edges, 7])  # 7 edge features
  senders_tensor = tf.random_uniform(minval=0, maxval=num_nodes, shape=[num_edges], dtype=tf.int32)
  receivers_tensor = tf.random_uniform(minval=0, maxval=num_nodes, shape=[num_edges], dtype=tf.int32)
  return {"globals": global_tensor, 
          "nodes": node_tensor, 
          "edges": edge_tensor, 
          "senders": senders_tensor, 
          "receivers": receivers_tensor}

batch_of_tensor_data_dicts = [get_random_graph_tensor_data_dict() for i in range(10)]  # This assumes you have a fixed batch size.
graphs_tuple = gn.utils_tf.data_dicts_to_graphs_tuple(batch_of_tensor_data_dicts)
```

So in principle you could build something similar to your `utils_tf.tensors_to_graphs_tuple` which takes as input your tensors, builds the relevant dictionaries and calls `utils_tf.data_dicts_to_graphs_tuple`.

If you really can't do it this way, then you could consider creating the `GraphsTuple` directly (I recommend understanding in depth the internals of the `GraphsTuple` before this, using the [graph nets basics demo](https://colab.research.google.com/github/deepmind/graph_nets/blob/master/graph_nets/demos/graph_nets_basics.ipynb)). You can just build individial GraphsTuples for each graph in the batch, and then concatenate them with `utils_tf.concat(..., axis=0)` to batch them together:

```
def get_random_graphs_tuple():
  num_nodes = tf.random_uniform(minval=10, maxval=20, shape=(), dtype=tf.int32)
  num_edges = tf.random_uniform(minval=50, maxval=100, shape=(), dtype=tf.int32)
  
  global_tensor = tf.zeros([5])  # 5 global features
  node_tensor = tf.zeros([num_nodes, 3])  # 3 node features
  edge_tensor = tf.zeros([num_edges, 7])  # 7 edge features
  senders_tensor = tf.random_uniform(minval=0, maxval=num_nodes, shape=[num_edges], dtype=tf.int32)
  receivers_tensor = tf.random_uniform(minval=0, maxval=num_nodes, shape=[num_edges], dtype=tf.int32)

  return gn.graphs.GraphsTuple(
      nodes=node_tensor,
      edges=edge_tensor,
      globals=global_tensor[tf.newaxis],  # Add batch axis.
      senders=senders_tensor,
      receivers=receivers_tensor,
      n_node=tf.shape(node_tensor)[0][tf.newaxis],  # Count the nodes, and add batch axis.
      n_edge=tf.shape(edge_tensor)[0][tf.newaxis],  # Count the edges, and add batch axis.
      )

list_of_graphs_tuples = [get_random_graphs_tuple() for i in range(10)]  # This assumes you have a fixed batch size.
graphs_tuple = gn.utils_tf.concat(list_of_graphs_tuples, axis=0)
```
If you can't assume you have a fixed batch size, then you can directly create a `GraphsTuple` with the batched graphs all at once, instead of using `utils_tf.concat`. In this case you would have to be careful to add offsets to the sender and receiver indices. (See [graph nets basics demo](https://colab.research.google.com/github/deepmind/graph_nets/blob/master/graph_nets/demos/graph_nets_basics.ipynb) and the implementation of `utils_tf.concat`).

**Comment by TianrenWang** [comment]
Thank you for your rapid response.

It did answer my question, but I have a new one. Let's say after I get my input features from my estimator, let's call it `features['x']`, where it has batch size `bs` and each sample has size 1, how would I make a GraphTuple object that has `bs` number of graphs, and each graph all share the same number of nodes, edges, and connectivity, but the features of all nodes for each graph correspond to the value of `features['x']`? So if I have `features['x'] = tensor([[1],[2],[3],[4]])` (batch size 4), how would I create a GraphTuple that has four graphs, where nodes for first graph are all 1, nodes for second graph are all 2, nodes for third graph are all 3.........?

**Comment by TianrenWang** [comment]
Nevermind, I figured out how this can be done. I am guessing you can just do something like graph.node = features['x'].

**Comment by alvarosg** [comment]
Yes, you can essentially build a new `GraphsTuple` using the approach I used in the previous example or use the `replace` method on an existing `GraphsTuple` instance, to replace one or more of the `GraphsTuple` fields. Note that this method does not modify in place, but, returns a new `GraphsTuple` where the fields have been replaced.
