### ISSUE TITLE
Inference - shortest path demo

### ISSUE THREAD

**Issue by amnt23** [deepmind/graph_nets#142]
Question about inference in the shortest path demo: suppose that I have a dataset composed by graphs with weighted edges and I want to find the shortest path between two nodes. How can I use the trained model to do it?

**Comment by alvarosg** [comment]
Thanks for your message. In the example the distance between the nodes is used in a way as the "weight" of the edge, as you want to avoid edges with longer distances to find the shortest path. So instead of using distances you could use your definition of weight to let the network take this into account.
