### ISSUE TITLE
Error occurred when converting a `graphs.GraphsTuple` to a sequence of networkx graphs

### ISSUE THREAD

**Issue by bkkblue** [deepmind/graph_nets#48]
An error occurred when I converted a GraphsTuple to a sequence of networkx graphs.The graphsTupe was produced by utils_tf.data_dicts_to_graphs_tuple(). And I used  utils_np.graphs_tuple_to_networkxs() to convert the GraphsTuple which produced by utils_tf , because I can't find graphs_tuple_to_networkxs() in utils_tf.
========================================================
the error:
AttributeError                            Traceback (most recent call last)
<ipython-input-36-721760894cd1> in <module>()
----> 7     graph_nx = utils_np.graphs_tuple_to_networkxs(num_elements_value)
AttributeError: 'list' object has no attribute 'n_node'
=======================================================
print the GraphTuple:
 print(num_elements_value)
[GraphsTuple(nodes=array([[0.8761827 ],
       [0.7522148 ],
       [0.6269338 ],
       [0.21133077],
       [0.9824985 ],
       [0.60169387],
       [0.63267815]], dtype=float32), edges=None, receivers=array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6], dtype=int32), senders=array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3,
       3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6,
       6, 6, 6, 6, 6], dtype=int32), globals=None, n_node=array([7], dtype=int32), n_edge=array([49], dtype=int32))]

There‘s a n_node in the GraphTuple.

**Comment by alvarosg** [comment]
Could you copy and paste the code you used to generate `num_elements_value`?

Two things I have noticed:
1. `num_elements_value` seems to be a list with a `GraphsTuple` rather than a `GraphsTuple`, which is why the error is generated, since it cannot access the `n_node` field of a list. Try calling `graph_nx = utils_np.graphs_tuple_to_networkxs(num_elements_value[0])`
2. If `num_elements_value` had been produced by `utils_tf.data_dicts_to_graphs_tuple` then it would contain tensors, not arrays, as you show in the print. I assume to get arrays you are using `sess.run`?
3. Is it possible that you did `num_elements_value = sess.run([graphs_tuple])` instead of `num_elements_value = sess.run(graphs_tuple)`?

There are additional examples of this in the graph_nets_basics demo notebook.

Hope this helps

**Comment by bkkblue** [comment]
Thanks for your help
I modified the code under your suggestions. I modified the "graphs_nx = utils_np.graphs_tuple_to_networkxs(num_elements_value)"  to  "graph_nx = utils_np.graphs_tuple_to_networkxs(num_elements_value[0])", and It worked.

3. Is it possible that you did num_elements_value = sess.run([graphs_tuple]) instead of num_elements_value = sess.run(graphs_tuple)?
-----Yes,
old code:
num_elements_op = utils_tf.make_runnable_in_session(num_elements_op)
with tf.Session() as sess:
    num_elements_value = sess.run([num_elements_op])
    print(num_elements_value)   
    graphs_nx = utils_np.graphs_tuple_to_networkxs(num_elements_value)

new code:
num_elements_op = utils_tf.make_runnable_in_session(num_elements_op)
with tf.Session() as sess:
    num_elements_value = sess.run(num_elements_op)
    print(num_elements_value)   
    graphs_nx = utils_np.graphs_tuple_to_networkxs(num_elements_value)

It's working very well now, on your advice.

Thanks for your help
