### ISSUE TITLE
Manipulating GraphsTuple placeholders in larger model

### ISSUE THREAD

**Issue by henryfriedlander** [deepmind/graph_nets#66]
I am working with your library to replace one of a modules in my tensorflow operations graph with your graph nets. However, as I have begun to work with your code, I have struggled for a couple of reason.

## Creating placeholders
First, (though this is not strictly speaking an error) it looks like in order to create a placeholder, we need to have a datapoint of a graph? This style seems eager. Is there some way to create a placeholder without knowing a template graph?

## Training the `graph_nets` module as part of a larger model
My second issue has been with training the `graphs_net` module as part of a larger model. We pass into the model a `graphs_dict` that we need to embed. 
- Given that we need to embed the nodes and edges of these graphs, we must of course be able to edit and assign them new values. I have tried fudging my way through it by trying to turn the underlying `graphs_tuple_placeholder` into a `graphs_dict`. This strategy did not work. When I try to manipulate the `graphs_tuple_placeholder`, the code raises `ValueError: setting an array element with a sequence`. What is the best way to manipulate the contents of these graph networks while the model is being built?

I understand a work-around could be to run the embedding layer separately, but I would like to keep my architecture end-to-end. Thank you.

**Comment by alvarosg** [comment]
Hi Henry!

> Is there some way to create a placeholder without knowing a template graph?

There are a couple of hidden methods (not supported officially) that allow creating placeholders using a specification of the graph, instead of a graph example.

*  [utils_tf._build_placeholders_from_specs](https://github.com/deepmind/graph_nets/blob/530aeadbc686f436e907ca8d111b5a72788906ee/graph_nets/utils_tf.py#L149)
*  [utils_tf._placeholders_from_graphs_tuple](https://github.com/deepmind/graph_nets/blob/530aeadbc686f436e907ca8d111b5a72788906ee/graph_nets/utils_tf.py#L196)

These methods are no supported officially, but are used internally by the other placeholder methods. You may want to try use them, but alternatively if you know the spect you can just easily build a dummy graph with zeros and use that to create the placeholders.

> Given that we need to embed the nodes and edges of these graphs, we must of course be able to edit and assign them new values.

Given a graphs.GraphsTuple object, you can easily replace the nodes by nodes embeddings:

`new graphs = graphs_tuple.replace(nodes=embedding network(graphs_tuple.nodes)`

You can also use `modules.GraphsIndependent` to learn/apply embeddings to nodes, edges and globals independently.

The only data-structure that we support for tensorflow graphs is the graphs.GraphsTuple filled tensors. So we don't have methods for converting them into data dicts with tensors. The reason we did not provide this is that graphs tuples may have a `None` batch size, so it would not be always possible to make it into a list of data dicts statically if the length of that list is not known and fixed statically.

Nevertheless, we do plenty of manipulation of the graphs directly in the graphs_tuple using the `replace` method. There are a few examples of this in the [graph nets basics demo](https://colab.research.google.com/github/deepmind/graph_nets/blob/master/graph_nets/demos/graph_nets_basics.ipynb). Also if you want to include a minimal example of runnable code, explaining what you want to achieve we would be happy to fill the gaps.

Hope this helps!

**Comment by plockxng** [comment]
Hi @alvarosg, thanks for your swift reply. I'm currently working with Henry on this issue and your advice has been helpful. 

We are able to run the graph network within our model now, but we seem to be struggling with being able to extract specific information from the individual graphs themselves. 

1. Is there a particular way to extract batch information from the `GraphsTuple` placeholder?
    - Our goal for doing this is to convert the graph structure back into a form so that we can create a tensor of shape `(batch_size, max_nodes_of_graphs_batch, emb_size)` and populate that tensor with the values within the `GraphsTuple` placeholder

1. What is the most effective way to backpropagate gradients through the `graph_net`/does `graph_net` do this step automatically with the larger tensorflow network?

**Comment by alvarosg** [comment]
1. You should be able to to some graph manipulation to achieve the desired effect. For example:
```
def separate_batch_and_node_axes(graphs_tuple, max_num_nodes=None):
  """Returns a tensor with separate batch and node axes.
  
  Args:
    graphs_tuple: graphs.GraphsTuple object.
    max_num_nodes: Dimension of the node axis of the output. It should
      be >= than the maximum number of nodes in any graph of the batch, If None,
      it will will be set dynamically to the maximum number
      of nodes in the batch.
    
  Returns:
    A tensor of shape [batch_size, max_num_nodes] + node_feature_shape padded
    with zeros.
  
  """
  
  # First index to scatter the nodes is the batch each node corresponds to.
  # E.g. If n_node is [3, 4, 1, 2]
  # batch_i = [0, 0, 0, 1, 1, 1, 1, 2, 3, 3]
  batch_size = tf.shape(graphs_tuple.n_node)[0]
  batch_i = utils_tf.repeat(tf.range(batch_size), graphs_tuple.n_node)
  
  # Second index to scatter the nodes is the position of each the node within 
  # the graph it belongs to.
  # E.g. If n_node is [3, 4, 1, 2]
  # batch_i = [0, 1, 2, 0, 1, 2, 3, 0, 0, 1]
  num_nodes = tf.shape(graphs_tuple.nodes)[0]
  node_batch_index = tf.range(num_nodes)
  num_previous_nodes = tf.cumsum(graphs_tuple.n_node) - graphs_tuple.n_node
  node_i = node_batch_index - utils_tf.repeat(num_previous_nodes, graphs_tuple.n_node)

  # Scatter the nodes to the right locations.
  indices = tf.cast(tf.stack([batch_i, node_i], axis=1), tf.int64)

  if max_num_nodes is None:
    max_num_nodes = tf.reduce_max(graphs_tuple.n_node)

  node_feature_shape = graphs_tuple.nodes.shape.as_list()[1:]
  output_shape = [batch_size, max_num_nodes] + node_feature_shape
    
  return tf.scatter_nd(indices, graphs_tuple.nodes, shape=output_shape)
```
That said, this operation may be expensive, so I would also think about 

I would reconsider if whatever operation you want to do afterwards, can also be done directly in the GraphsTuple representation.

2. The GraphNets model is fully differentiable, `tf.gradients` does the right thing, so the optimizers in tensorflow should automatically do the backpropagation for you as usual.

Hope this helps :)

**Comment by plockxng** [comment]
> Hope this helps :)

Yes! We got things working thanks to you :] Thank you very much @alvarosg!

And for reference for anyone else who may have issues, this was the changes required to make the above function work correctly for us:

```python
def separate_batch_and_node_axes(graphs_tuple, max_num_nodes=None):
    """Returns a tensor with separate batch and node axes.

    Args:
    graphs_tuple: graphs.GraphsTuple object.
    max_num_nodes: Dimension of the node axis of the output. It should
    be >= than the maximum number of nodes in any graph of the batch, If None,
    it will will be set dynamically to the maximum number
    of nodes in the batch.

    Returns:
    A tensor of shape [batch_size, max_num_nodes] + node_feature_shape padded
    with zeros.
    """

    # First index to scatter the nodes is the batch each node corresponds to.
    # E.g. If n_node is [3, 4, 1, 2]
    # batch_i = [0, 0, 0, 1, 1, 1, 1, 2, 3, 3]
    batch_size = tf.shape(graphs_tuple.n_node)[0]
    batch_i = utils_tf.repeat(tf.range(batch_size), graphs_tuple.n_node)

    # Second index to scatter the nodes is the position of each the node within
    # the graph it belongs to.
    # E.g. If n_node is [3, 4, 1, 2]
    # node_i = [0, 1, 2, 0, 1, 2, 3, 0, 0, 1]
    num_nodes = tf.shape(graphs_tuple.nodes)[0]
    node_batch_index = tf.range(num_nodes)
    num_previous_nodes = tf.cumsum(graphs_tuple.n_node) - graphs_tuple.n_node
    node_i = node_batch_index - utils_tf.repeat(num_previous_nodes, graphs_tuple.n_node)

    # Scatter the nodes to the right locations.
    # indices = [[0,0], [0,1], [0,2], [1,0], [1,1], [1,2], [1,3], [2,0], [3,0], [3,1]]
    indices = tf.cast(tf.stack([batch_i, node_i], axis=1), tf.int32)

    if max_num_nodes is None:
     max_num_nodes = tf.reduce_max(graphs_tuple.n_node)

    node_feature_shape = graphs_tuple.nodes.shape.as_list()[1:]
    # Create output_shape tensor
    output_shape = tf.stack([batch_size, max_num_nodes], axis=0)
    output_shape = tf.concat([output_shape, tf.convert_to_tensor(node_feature_shape)], axis=0)

    return(tf.scatter_nd(indices, graphs_tuple.nodes, shape=output_shape))
```
