### ISSUE TITLE
using word embedding features as node and edge features

### ISSUE THREAD

**Issue by ronsoohyeong** [deepmind/graph_nets#75]
Hi,
I am trying to use graph_nets for the case where there is a graph of one-word nodes and one-word edges for each example in a batch, and the node and edge features are from the word embeddings that are learnable.
The usual way to use word embedding is to get the symbol id's as the feed dict, then pass it through tf.nn.embedding_lookup, and use the resulting tensor of shape (batch size, text length, word embedidng dimension) in the downstream model.
In this case the output tensor of tf.nn.embedding_lookup has the shape of (batch size, number of nodes, word embedding dimension) for the node features, and (batch size, number of edges, word embedding dimension) for the edge features.
I am stuck at this point not knowing how to make a GraphTuple from those and the sender and receiver tensors of shape (batch size, number of edges,).

Alternative way of creating GraphTuples by utils_np doesn't seem to be applicable since the word embedidng features are not available at the numpy level.
Can you please help?

Best regards,
Ron

**Comment by alvarosg** [comment]
If I understand correctly what you are saying (let me know if I missed any details), your dataset consists of:
* A vocabulary with M words
* A set of graphs each of them containing one word from the vocabulary at each node, and also one word at each edge.

What I think you need in this case is to create a GraphsTuple with a single integer feature in each node and a single integer feature in each edges. This integer would represent the id of the word contained in the node/edge as specified in the vocabulary.

This will lead to a GraphsTuple with tensors: 
* nodes: (`Tensor([None, 1], tf.int32)`) # None indicates the total number of nodes in the batch
* edges: (`Tensor([None, 1], tf.int32)`) # None indicates the total number of edges in the batch

where `None` indicaes

Assuming your lookup table of embeddings is something like: 
* embeddings_table: (`Tensor([M, embedding_size]), tf.float32)`)

Then in order to look up the embeddings you would just need to do to graph all nodes, and all edges one by one from the lookup table, and set the corresponding embeddings as the new nodes:
```
graphs_tuple_of_embeddings = graphs_tuple.replace(
  nodes=tf.nn.embedding_lookup(embeddings_table, graphs_tuple.nodes[:, 0]),
  edges=tf.nn.embedding_lookup(embeddings_table, graphs_tuple.edges[:, 0])
)
```

And you will get something out with shape:
This will lead to a GraphsTuple with tensors: 
* nodes: (`Tensor([None, embedding_size], tf.float32)`)
* edges: (`Tensor([None, embedding_size], tf.float32)`)

If you want to use placeholders, then you should be able to follow [this tutorial](https://colab.sandbox.google.com/github/deepmind/graph_nets/blob/master/graph_nets/demos/graph_nets_basics.ipynb#scrollTo=lQVz4xCbXr_J). This tutorial also has examples of how to build the data_dicts, the only difference is that in your case you would have a single node/edge feature which will be an integer instead of a float32.

Hope this helps!

**Comment by ronsoohyeong** [comment]
Thanks. It worked. Let me close this for now until it turns out otherwise.
