### ISSUE TITLE
Any development under way?

### ISSUE THREAD

**Issue by thinkingparticle** [deepmind/graph_nets#86]
The paper is great. But I wanted to ask if there is any plan to develop this project? 
If I wanted to learn a graph framework, should I invest time to learn this or others like https://github.com/dmlc/dgl ? last commit was 4 months ago.

**Comment by gncs** [comment]
Good question! I would also like to know if the development team has any plans to update this code to be compatible with TF 2.0?

**Comment by alvarosg** [comment]
Thanks for your messages, see some replies below. Hope this helps!

> The paper is great. But I wanted to ask if there is any plan to develop this project?
> If I wanted to learn a graph framework, should I invest time to learn this or others like https://github.com/dmlc/dgl ? last commit was 4 months ago.

We have been actively replying to issues, we actively use this library internally, there is indeed plans to keep supporting it, and we are always looking for suggestions ideas for what to add :) . 

With respect to what framework/library to use, that would probably depend on what you want exactly (e.g.  TensorFlow or PyTorch). I think in any case learning about any graph library is a good idea to start understanding the challenges of working with graphs, however, this library is particularly interesting because it is built bottom up from what we think are the most basic building blocks of any graph neural network, as explained in the paper.

> Good question! I would also like to know if the development team has any plans to update this code to be compatible with TF 2.0?

Yes, the plan is definitely to support TF 2.0. Currently [Sonnet 2](https://github.com/deepmind/sonnet) (one of our dependencies) is still in beta, but hopefully we will be able to update it shortly after Sonnet 2 is officially released.

**Comment by thinkingparticle** [comment]
>  this library is particularly interesting because it is built bottom up from what we think are the most basic building blocks of any graph neural network, as explained in the paper.

Thanks. I agree and that's why I asked. Because other libraries are not based on the framework provided in the paper.

Can you provide an example of below part of paper? 
In paper the attribute is defined as:
> Attribute : properties that can be encoded as a vector, set, or **_even another graph._**

image below:
![image](https://user-images.githubusercontent.com/17741554/64543763-06ac5800-d33b-11e9-8774-f8e219e78488.png)

Can you provide an example implementation of attributes of nodes/edges of a graph, where each attribute is a graph? (using this library)

**Comment by alvarosg** [comment]
The problem of having graph attributes to be other graphs, is that it starts entering the territory of hierarchical models, and there are no canonical ways to uniquely specify what is the right way to do this (e.g. when to run message passing on the lo level feature graphs, or on the main graph, and how to share information between the two.).

But yes the library definitely supports building a hierarchical model, it just requires a bit more of bookkeeping (probably keeping multiple GraphTuples for the different levels of hierarchy) and advanced manipulation of the GraphsTuple fields to send information from one level of hierarchy to the other.

**Comment by jmsfltchr** [comment]
Just to share that there are libraries depending upon graph_nets. Our [KGCN](https://github.com/graknlabs/kglib/tree/master/kglib/kgcn) project as part of [KGLIB](https://github.com/graknlabs/kglib) is dedicated to this kind of learning over knowledge graphs. It heavily leverages graph_nets. :)

**Comment by alvarosg** [comment]
TensorFlow compatibility is now live :)

Here's a link to a [demo](https://colab.research.google.com/github/deepmind/graph_nets/blob/master/graph_nets/demos_tf2/sort.ipynb).

TF1 and Sonnet1 is still fully supported, the library will just take into account with version of Sonnet is installed in the system and change the base class for the Sonnet modules according to that. Please do report back any issues you may find, feedback is always appreciated!
